# Changes here will be overwritten by Copier
_commit: v0.1.6
_src_path: https://gitlab.softwareheritage.org/swh/devel/swh-py-template.git
description: Software Heritage core utilities
distribution_name: swh-core
have_cli: true
have_workers: false
package_root: swh/core
project_name: swh.core
python_minimal_version: '3.7'
readme_format: rst
